CREATE DATABASE [SISGEN_DB]

USE [SISGEN_DB]	

CREATE TABLE [dbo].[REGISTRO](

    [ID] INT NOT NULL identity(1, 1),
	[NOMBRE] VARCHAR(40),
	[APELLIDO] VARCHAR(40),
	[NOMBRE_USUARIO] VARCHAR(40),
	[PASS] VARCHAR(40),
	[REP_PASS] VARCHAR(40),

)

CREATE TABLE [dbo].[LOGIN2](
	[ID] INT NOT NULL IDENTITY(1, 1),
	[USUARIO] VARCHAR(40),
	[PASS] VARCHAR(40),
	CONSTRAINT [PK_ID] PRIMARY KEY ([ID]),
)

alter table LOGIN2

ADD CONSTRAINT [FK_ID1] FOREIGN KEY ([USUARIO]) REFERENCES [REGISTRO] ([NOMBRE_USUARIO])

CREATE TABLE [dbo].[CONTROL_CLIENTES](

	[ID] INT NOT NULL identity(1, 1),
	[NUM_CASO] INT  NOT NULL,
	[CLIENTE] VARCHAR(40) NOT NULL,
	[FECHA] DATE NOT NULL,
	[CODIGO_CLIENTE] INT NOT NULL,
	[REP_DGA] INT NOT NULL,
	[GES_DGA] INT NOT NULL,
	[ENLACE_CLIENTE] INT NOT NULL,
	[PRES_DEC] INT NOT NULL,
	[VER_MER] INT NOT NULL,
	[PERSONA_RESPONSABLE] VARCHAR(40) NOT NULL,
	[ESTATUS] VARCHAR(40) NOT NULL,

)

SELECT LOGIN2.USUARIO, REGISTRO.PASS FROM REGISTRO 
INNER JOIN LOGIN2 ON LOGIN2.ID = REGISTRO.ID

SELECT * FROM LOGIN

SELECT * FROM LOGIN
SELECT * FROM REGISTRO

SELECT USUARIO  FROM LOGIN2 l
LEFT JOIN REGISTRO r ON l.USUARIO = r.APELLIDO
